name: Docs update

on:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - packages/chakra-components/docs/**

jobs:
  job_docs_update:
    if: github.actor != 'arabot-1'
    permissions: read-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout components-ui repo
        uses: actions/checkout@v3

      - name: Generate 01-Intro.md # It appends the content of the README.md and fixes relative inks
        run: |
          cd packages/chakra-components/docs
          cat ../README.md >> ./01-Intro.md
          sed -i 's#]: ./#]: https://github.com/vocdoni/vocdoni-sdk/blob/main/#g' ./01-Intro.md

      - name: Get short commit hash
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Checkout developer-portal repo
        uses: actions/checkout@v3
        with:
          repository: vocdoni/developer-portal
          ref: main
          path: developer-portal

      - name: Copy generated docs
        run: |
          rm -rf ./developer-portal/docs/ui-components/
          mkdir -p ./developer-portal/docs/ui-components/
          cp -R ./* ./developer-portal/docs/ui-components/

      - name: Create PR to developer-portal repo
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.VOCDONIBOT_PAT }}
          path: developer-portal
          commit-message: 'Update ui-components docs by commit ${{ steps.vars.outputs.sha_short }}'
          committer: 'Arabot-1 <arabot-1@users.noreply.github.com>'
          base: main
          branch: update-ui-components-docs
          delete-branch: true
          title: Update docs with ui-components repo changes
          body: |
            * This is an automated pull request to upload the updated ui-components documentation.
            * GitHub Action Run: [${{ github.run_id }}](https://github.com/vocdoni/vocdoni-sdk/actions/runs/${{ github.run_id }})
          labels: |
            automated pr
          reviewers: ${{ github.actor }}
          team-reviewers: SdkDocsReviewer # This is still valid

      - name: Check PR outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
